version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - ./frontend:/usr/app
      # - /usr/app/node_modules
    stdin_open: true
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    container_name: app_backend
    volumes:
      - ./backend:/usr/app
      # - /usr/app.node_modules
  mysql:
    platform: linux/x86_64
    build: ./mysql
    restart: unless-stopped
    container_name: app_mysql
    ports:
      - "3308:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: formegusto
      MYSQL_DATABASE: formeapp
